interface ItemResult {
  category: string;
  description: string;
  quantity: number;
  insuranceOffer: number;
  fmvPrice: number;
  additionalAmount: number;
  percentageIncrease: number;
  status: 'underpaid' | 'fair';
}

interface RegionalContext {
  femaClaimCount: number;
  avgFEMAPayment: number;
  inflationAdjustment: number;
  topComplaints: Array<{ company: string; count: number }>;
}

interface AnalysisResponse {
  zipCode: string;
  items: ItemResult[];
  summary: {
    totalInsuranceOffer: number;
    totalFMV: number;
    totalAdditional: number;
    overallIncrease: number;
  };
  regionalContext?: RegionalContext;
}

export function generateEmailReportSummary(results: AnalysisResponse): string {
  const lines: string[] = [];

  // Header
  lines.push("MAX-CLAIM - Fair Market Value Insurance Claim Analysis");
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(`Report Date: ${new Date().toLocaleDateString()}`);
  lines.push(`Analysis Location: ZIP Code ${results.zipCode}`);
  lines.push("");

  // Summary
  lines.push("CLAIM SUMMARY");
  lines.push("-".repeat(60));
  lines.push(`Insurance Company Offer: $${results.summary.totalInsuranceOffer.toLocaleString('en-US', { minimumFractionDigits: 2 })}`);
  lines.push(`Fair Market Value (FMV): $${results.summary.totalFMV.toLocaleString('en-US', { minimumFractionDigits: 2 })}`);
  lines.push(`Additional Amount You Deserve: $${results.summary.totalAdditional.toLocaleString('en-US', { minimumFractionDigits: 2 })}`);
  lines.push(`Percentage Increase: ${results.summary.overallIncrease.toFixed(1)}%`);
  lines.push("");

  // Itemized Breakdown
  lines.push("ITEMIZED BREAKDOWN");
  lines.push("-".repeat(60));
  results.items.forEach((item, index) => {
    lines.push(`Item ${index + 1}: ${item.category} - ${item.description}`);
    lines.push(`  Quantity: ${item.quantity}`);
    lines.push(`  Insurance Offer: $${item.insuranceOffer.toLocaleString('en-US', { minimumFractionDigits: 2 })}`);
    lines.push(`  Fair Market Value: $${item.fmvPrice.toLocaleString('en-US', { minimumFractionDigits: 2 })}`);
    lines.push(`  Additional Amount: $${item.additionalAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })} (+${item.percentageIncrease.toFixed(1)}%)`);
    lines.push(`  Status: ${item.status === 'underpaid' ? 'UNDERPAID' : 'Fair Offer'}`);
    lines.push("");
  });

  // Regional Context
  if (results.regionalContext) {
    lines.push("REGIONAL INSURANCE DATA");
    lines.push("-".repeat(60));

    if (results.regionalContext.femaClaimCount > 0) {
      lines.push(`Historical FEMA Claims: ${results.regionalContext.femaClaimCount}`);
      if (results.regionalContext.avgFEMAPayment > 0) {
        lines.push(`Average FEMA Payment: $${results.regionalContext.avgFEMAPayment.toLocaleString()}`);
      }
    }

    if (results.regionalContext.inflationAdjustment !== 0) {
      lines.push(`Construction Cost Inflation (YoY): ${results.regionalContext.inflationAdjustment > 0 ? '+' : ''}${results.regionalContext.inflationAdjustment}% (BLS)`);
    }

    if (results.regionalContext.topComplaints && results.regionalContext.topComplaints.length > 0) {
      lines.push("");
      lines.push("Most Complained About Insurers (Texas DOI):");
      results.regionalContext.topComplaints.forEach((complaint) => {
        lines.push(`  - ${complaint.company}: ${complaint.count} complaints`);
      });
    }
    lines.push("");
  }

  // Resources
  lines.push("ASSISTANCE & DISASTER RELIEF RESOURCES");
  lines.push("-".repeat(60));
  lines.push("- FEMA Disaster Assistance: www.fema.gov/assistance/individual/program");
  lines.push("- Local 211 Services: www.211.org");
  lines.push("- Texas Homeowner Assistance: www.texashomeownerassistance.com");
  lines.push("- HUD Repair Programs: www.hud.gov/info/disasterresources");
  lines.push("- BLS Replacement Cost Index: www.bls.gov/ppi");
  lines.push("- TDI Insurance Complaints: data.texas.gov/dataset/Insurance-Complaints-All-Data");
  lines.push("");

  // Footer
  lines.push("=".repeat(60));
  lines.push("Generated by Max-Claim - Free Consumer Advocacy Tool");
  lines.push("");
  lines.push("DISCLAIMER: This is an educational tool providing estimated fair market");
  lines.push("values for informational purposes only. Not professional advice.");
  lines.push("For the complete PDF report with full legal disclaimers,");
  lines.push("please visit Max-Claim and use the Download PDF feature.");
  lines.push("");
  lines.push("Max-Claim is a free privacy-first consumer advocacy platform.");
  lines.push("We never collect personally identifiable information.");

  return lines.join("\n");
}
